In [20]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

RANDOM_STATE = 5

b = datasets.load_breast_cancer()
(X_all, y_all) = b.data, b.target
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.25, random_state=RANDOM_STATE)

In [21]:
n = KNeighborsClassifier(n_neighbors=5)
n.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [22]:
print("SCIKIT train score", n.score(X_train, y_train))
print("SCIKIT test score", n.score(X_test, y_test))

SCIKIT train score 0.9413145539906104
SCIKIT test score 0.951048951048951


In [38]:
import numpy as np

NUMBER_NEIGHBORS = 5

def group_prediction(y_hat):
  if y_hat >= 0.5:
    return 1
  else:
    return 0

def euclidean_distance(xi, xj):
  return (np.linalg.norm(xi - xj))

for xi in X_train:
  dist = np.apply_along_axis(euclidean_distance, 1, X_train, xi)
  sorted_dist_indexes = np.argsort(dist)
  neighbors = sorted_dist_indexes[1:NUMBER_NEIGHBORS+1]
  mean_label = y_train[neighbors].mean()
  print(neighbors)
  print(y_train[neighbors].mean())
  print(group_prediction(mean_label))

[202 346 384  86 314]
0.0
0
[181 170 330 282 159]
1.0
1
[237  10 122 283 360]
1.0
1
[ 84 300 175 380 251]
1.0
1
[120 182 294 208 262]
0.0
0
[ 41 135 420 364 200]
1.0
1
[106 216 374  39 248]
1.0
1
[ 33 367 107 267  50]
1.0
1
[278 355 306 351  30]
0.0
0
[290 212 281 123 118]
1.0
1
[122 237 140 127   2]
1.0
1
[176  54 116  37 338]
1.0
1
[ 88 209 150  98 229]
0.0
0
[259 145  20  64 112]
1.0
1
[199 321  99 405 266]
1.0
1
[408 124 311  25 297]
0.4
0
[193 340 336  25 101]
1.0
1
[139 192 116  37  11]
1.0
1
[ 27 397 308 243 256]
1.0
1
[217 352 112  96 417]
1.0
1
[145  13 259 225 361]
1.0
1
[302 359  81 320 207]
0.0
0
[262 207 401 208  58]
0.0
0
[101 409  25 241 285]
0.8
1
[337 113 198  87 188]
1.0
1
[101 409  23 124 408]
0.8
1
[133  50 267  79 305]
1.0
1
[308  18 397 256 243]
1.0
1
[413 421  67 166 164]
0.4
0
[173 121 128 395 195]
1.0
1
[351  47 193 335 271]
0.6
1
[349 300 260 264 219]
1.0
1
[376 118 290   9 268]
1.0
1
[ 50 367   7 267 133]
1.0
1
[385 181   1 316 170]
1.0
1
[362 367 267 133  50